package troubleshoot.states;

public enum ResourceCertificateField
{
	VERSION_KEY,
	DATE_AND_TIME_KEY,
	FILE_ID_KEY,
	HARDWARE_COMPATIBILITY_KEY,
	VENDOR_NAME_KEY,
	PRODUCT_BOARD_NAME_KEY,
	APPLICATION_VERSION_KEY,
	TYPE_KEY,
	RES_INFO_KEY,
	X509_CHAIN_KEY,
	OTHER;
}
