package troubleshoot.states;

public enum ROMFSCertificate
{
	TYPE_KEY,
	PCI_KEY,
	FILE_ID_KEY,
	VENDOR_NAME_KEY,
	PRODUCT_BOARD_NAME_KEY,
	APPLICATION_NAME_KEY,
	APPLICATION_VERSION_KEY,
	DATE_AND_TIME_KEY,
	HARDWARE_COMPATIBILITY_KEY,
	VERSION_KEY,
	SIG_KEY,	
	PRODUCT_CONFIG_KEY,
	BUILD_NUMBER_KEY,
	X509_CHAIN_KEY,
	PCIAPP_KEY,	
	SIG_READER_BIN_KEY,
	OTHER;
}
